### ISSUE TITLE
USB device is connected to companion, but idevicerestore doesn't work

### ISSUE THREAD

**Issue by Anonymous941** [ChefKissInc/QEMUAppleSilicon#67]
I followed the instructions in the wiki, including applying the patch and building libimobiledevice from source that I checked out only a few hours ago.  I also read #60 but none of the fixes there are working. Running `lsusb` in the companion shows the device is definitely connected:

```plain
$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 05ac:12a8 Apple, Inc. iPhone 5/5C/5S/6/SE
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

However `idevicerestore` always fails without printing anything.  Here is the last part of the iOS device's log:

```plain
000011.078030 AppleT8027USBXDCI@: IOUSBDeviceController::gated_registerFunction: register function AppleUSBMux
000011.078535 AppleT8027USBXDCI@: IOUSBDeviceController::startUSBStack: starting usb stack
000011.080440 AppleT8027USBXDCI@0: IOUSBDeviceController::startUSBStack: not connected
000011.081089 AppleT8027USBXDCI@0: AppleUSBXDCI::goOnBus: not on bus
000011.084161 AppleT8027USBXDCI@0: AppleUSBXDCIARM::cableChangeOccurred: cable detect disabled: transport type 2 connect type 2 restricted mode _lastRestrictedMode 0
000011.085935 AppleT8027USBXDCI@0: AppleUSBXDCIARM::cableChangeOccurred: powering on for transport type 2 connect type 2 restricted mode 0
000011.446911 AppleT8027USBXDCI@0: IOUSBDeviceController::setupDeviceSetAddress: setting USB device address 4
000011.490569 AppleT8027USBXDCI@4: IOUSBDeviceController::setupDeviceSetConfiguration: configuration 0 -> 1
AppleUSBDeviceMux::message - kMessageInterfaceWasActivated
IOReturn AppleUSBDeviceMux::setPropertiesGated(OSObject *) setting debug level to 7
[20:03:26.0798-GMT]{4>7} CHECKPOINT END: MAIN:[0x040E] enable_usb
restore-step-ids = {}
restore-step-names = {}
restore-step-uptime = 11
restore-step-user-progress = 0
waiting for host to trigger start of restore [timeout of 120 seconds]
```

I tried using `sudo`, recompiling several times, and removing the `-i 0x1122334455667788` parameter (because it filters).  It always shows this:

```plain
Using ApTicket found at root_ticket.der length 8931
idevicerestore 1.0.0-231-ga5905b7-dirty (libirecovery 1.2.1-13-g638056a, libtatsu 1.0.5)
ERROR: Unable to discover device mode. Please make sure a device is attached.
```

**Comment by aellul27** [comment]
Hi, are you using the latest libimobiledevice? I believe a fix was pushed in that repo for this issue. If you are, refer to VisualEhrmanntraut's advice: 
> downgrade libimobiledevice to commit 72456f2, seems something between 009b982 and the commit after 72456f2 broke something
>  

 _Originally posted by @VisualEhrmanntraut in [#60](https://github.com/ChefKissInc/QEMUAppleSilicon/issues/60#issuecomment-2965703309)_

run`git checkout 72456f2` in your libimobiledevice directory

**Comment by Anonymous941** [comment]
Still not working, but I've got some interesting logs when I try to restore:

```plain
libMobileGestalt MobileGestalt.c:711: RestoreLog: Client Query: UniqueDeviceID
2025-06-12 21:33:03.112548+0000 restored_external[7:443] RestoreLog: Client Query: UniqueDeviceID
libMobileGestalt MobileGestalt.c:711: RestoreLog: Client Query: nFRqKto/RuQAV1P+0/qkBA
2025-06-12 21:33:03.115149+0000 restored_external[7:443] RestoreLog: Client Query: nFRqKto/RuQAV1P+0/qkBA
libMobileGestalt MobileGestalt.c:711: RestoreLog: Client Query: TF31PAB6aO8KAbPyNKSxKA
2025-06-12 21:33:03.119000+0000 restored_external[7:443] RestoreLog: Client Query: TF31PAB6aO8KAbPyNKSxKA
libMobileGestalt MobileGestalt.c:743: RestoreLog: Client Response: TF31PAB6aO8KAbPyNKSxKA : 1234605616436508552
2025-06-12 21:33:03.124457+0000 restored_external[7:443] RestoreLog: Client Response: TF31PAB6aO8KAbPyNKSxKA : 1234605616436508552
libMobileGestalt MobileGestalt.c:711: RestoreLog: Client Query: 566JrJVMlDfnslGpwUzNlQ
2025-06-12 21:33:03.126679+0000 restored_external[7:443] RestoreLog: Client Query: 566JrJVMlDfnslGpwUzNlQ
libMobileGestalt MobileGestalt.c:743: RestoreLog: Client Response: 566JrJVMlDfnslGpwUzNlQ : 32789
2025-06-12 21:33:03.132302+0000 restored_external[7:443] RestoreLog: Client Response: 566JrJVMlDfnslGpwUzNlQ : 32789
libMobileGestalt MobileGestalt.c:743: RestoreLog: Client Response: nFRqKto/RuQAV1P+0/qkBA : <CFData 0x105d10930 [0x1027a41b8]>{length = 25, capacity = 25, bytes = 0x30303030383031352d31313232333334 ... 3535363637373838}
2025-06-12 21:33:03.154624+0000 restored_external[7:443] RestoreLog: Client Response: nFRqKto/RuQAV1P+0/qkBA : {length = 25, bytes = 0x30303030 38303135 2d313132 32333334 ... 35353636 37373838 }
libMobileGestalt MobileGestalt.c:743: RestoreLog: Client Response: UniqueDeviceID : 00008015-1122334455667788
2025-06-12 21:33:03.158272+0000 restored_external[7:443] RestoreLog: Client Response: UniqueDeviceID : 00008015-1122334455667788
000151.890169 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice: configuration: Apple Mobile Device
000151.891196 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice:    interface: AppleUSBMux
000151.892497 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice: configuration: Reserved 1 + Apple Mobile Device
000151.893462 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice:    interface: Reserved
000151.894240 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice:    interface: AppleUSBMux
000151.894818 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice: configuration: Reserved 2 + Apple Mobile Device
000151.895475 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice:    interface: Reserved
000151.896003 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice:    interface: AppleUSBMux
000151.896546 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice: configuration: Reserved 3 + Apple Mobile Device
000151.897193 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice:    interface: Reserved
000151.897710 AppleT8027USBXDCI@: IOUSBDeviceController::createUSBDevice:    interface: AppleUSBMux
waiting for matching IOKit service: {
000151.907946 AppleT8027USBXDCI@: IOUSBDeviceController::gated_registerFunction: register function Reserved

}
AppleUSBDeviceMux build: Aug 12 2020 22:50:42
000151.917293 AppleT8027USBXDCI@: IOUSBDeviceController::gated_registerFunction: register function AppleUSBMux
000151.918011 AppleT8027USBXDCI@: IOUSBDeviceController::startUSBStack: starting usb stack
000151.921110 AppleT8027USBXDCI@0: IOUSBDeviceController::startUSBStack: not connected
000151.921998 AppleT8027USBXDCI@0: AppleUSBXDCI::goOnBus: not on bus
000151.925342 AppleT8027USBXDCI@0: AppleUSBXDCIARM::cableChangeOccurred: cable detect disabled: transport type 2 connect type 2 restricted mode _lastRestrictedMode 0
000151.926215 AppleT8027USBXDCI@0: AppleUSBXDCIARM::cableChangeOccurred: powering on for transport type 2 connect type 2 restricted mode 0
Unable to read from socket: Bad file descriptor
000152.313726 AppleT8027USBXDCI@0: IOUSBDeviceController::setupDeviceSetAddress: setting USB device address 3
000152.370601 AppleT8027USBXDCI@3: IOUSBDeviceController::setupDeviceSetConfiguration: configuration 0 -> 1
AppleUSBDeviceMux::message - kMessageInterfaceWasActivated
IOReturn AppleUSBDeviceMux::setPropertiesGated(OSObject *) setting debug level to 7
[21:33:06.0196-GMT]{4>7} CHECKPOINT END: MAIN:[0x040E] enable_usb
restore-step-ids = {}
restore-step-names = {}
restore-step-uptime = 13
restore-step-user-progress = 0
waiting for host to trigger start of restore [timeout of 120 seconds]
```

**Comment by aellul27** [comment]
Run 'journalctl -u usbmuxd' and show the output

**Comment by Anonymous941** [comment]
Issue solved!  I was using Void Linux because it's lightweight and it uses runit, which doesn't start `usbmuxd` on startup.  I started it manually and now it restored.  Thanks for your help
